import data

def hangplay():
  print('     ╔═════╗  ')
  print('     ║     █  ')
  print('     ║     │  ')
  print('     ║ ' + data.man[0])
  print('     ║ ' + data.man[1])
  print('     ║ ' + data.man[2])
  print('     ║ ' + data.man[3])
  print('     ║        ')
  print('     ║        ')
  print('    ▀▀▀       ')



# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║     O  ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║     O  ')
# print(' ║     |  ')
# print(' ║     |  ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║     O  ')
# print(' ║    \|  ')
# print(' ║     |  ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║     O  ')
# print(' ║    \|/ ')
# print(' ║     |  ')
# print(' ║        ')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║     O  ')
# print(' ║    \|/ ')
# print(' ║     |  ')
# print(' ║    /   ')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

# print(' ╔═════╗  ')
# print(' ║     █  ')
# print(' ║     │  ')
# print(' ║     O  ')
# print(' ║    \|/ ')
# print(' ║     |  ')
# print(' ║    / \\')
# print(' ║        ')
# print(' ║        ')
# print('▀▀▀       ')

